# Generated by Django 5.1.6 on 2025-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toapp', '0002_registeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
