# Generated by Django 5.1.6 on 2025-02-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toapp', '0003_registeration_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(max_length=5)),
            ],
        ),
    ]
